### ISSUE TITLE
Responsive behavior of the side menus do not work on mobile technologies

### ISSUE THREAD

**Issue by alessio-alfonsetti** [slms4redd/portal#5]
The menu for the layers do not properly work:
- on both Android and IOS (mobile phones) it is not possible to hide it to the left. In some cases the layers contained in the menu disappear, but the grey menu form keeps staying where it is making it uncomfortable to visit the portal.

The menu for the legend does not show up at all on both IOS (IPhone) and Android phone. 

Tests on tablets have not been provided yet.

**Comment by minotogna** [comment]
The geo-portal has never meant to be mobile-compatible.
On such small devices, a new UI  must be developed.

**Comment by minotogna** [comment]
The UI has been tested on tablet with horizontal layout with resolution 1024 x 600

**Comment by Damianofds** [comment]
Mobile compatibility hasn't been a requirement of the geoportal but a graceful degradation is always desirable. 
Although the old user interface is not responsive it still works in all of its basic features on major devices, this version instead has unexpected and sometimes unpredictable behaviours under a resolutions with width or height under 1000 px.

A possible (not painful I think) solutions could be to deactivate the UI components under a certain resolution and show an alert saying "this resolutions is not fully supported"

**Comment by minotogna** [comment]
Hi Damiano, 
Thanks for the suggestion. I'll try to add the message for xs screens. And will test it with other smaller tablet screen resolutions
Regards 
Mino 
On Aug 10, 2015 5:25 PM, Damiano Giampaoli <notifications@github.com> wrote:



Mobile compatibility hasn't been a requirement of the geoportal but a graceful degradation is always desirable.

Although the old user interface is not responsive it still works in all of its basic features on major devices, this version instead has unexpected and sometimes unpredictable behaviours under a resolutions with width or height under 1000 px.
A possible (not painful I think) solutions could be to deactivate the UI components under a certain resolution and show an alert saying "this resolutions is not fully supported"
—
Reply to this email directly or 
view it on GitHub.

**Comment by Damianofds** [comment]
Tested on iPad and sony xperia with android 4.4.2 it works good, on small devices the dashboard is not visible.
